StudentHomepage/config/routes.rb
StudentHomepage::Application.routes.draw do
  resources :clubs
  resources :students
  resources :instructors

  get 'session' => "home#index"
  get 'login' => "login#new"
  post 'login' => "login#create"
  get 'logout' => "login#destroy"
  get 'register' => "users#new"
  post 'register' => "users#create"
  get 'contact' => "contact#new"
  post 'contact' => "contact#create"

  

  root 'login#new'

end

StudentHomepage/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to session_path
    else
      flash.now[:invalid_login] = "Invalid Username or Password!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:logged_out] = "User Has Been Logged Out"
    redirect_to root_url
  end
end

StudentHomepage/app/helpers/login_helper.rb
module LoginHelper
end

StudentHomepage/app/views/login/new.html.erb
<!doctype html>
<html>
<head>
        <link rel="shortcut icon" type="image/icon" href="/favicon.ico"/>
        <link rel="shortcut icon" type="image/icon" href="StudentHomepage/public/favicon.ico"/>
        <%= javascript_include_tag 'application' %>
        <%= stylesheet_link_tag 'application' %>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"  name="viewport" />
</head>
<body>
  <div id="header"></div>
  <div id="menu">
    <% flash.each do |key,msg| %>
	<script>alert('<%= msg %>')</script>
    <% end %>
    <div id="login_container">
      <%= form_tag login_path do %>
        <br><%= label_tag :username, "Username:", class: "form" %><br>
        <%= text_field_tag :username, nil, class: "form" %><br><br>
        <%= label_tag :password, "Password:", class: "form" %><br>
        <%= password_field_tag :password, nil, class: "form" %><br><br>
        <%= submit_tag "Login", class: "submit_button" %>
        <%= button_tag(type: 'button', class: 'cancel_button') do content_tag(:strong, 'Cancel') end %><br><br>
      <% end %>
      <button type="button" id="forgot_password_button">Forgot Password?</button><br><br>
    </div>
    <div id="forgot_password_container">
      <%= form_for Message.new, :validate => true, :html => {:id => "forgot_pass_form"}, :url => contact_path do |form| %>
          <br><%= form.label :email %>
          <input id="message_email" name="message[email]" type="email" required>
          <%= form.submit "Send" %><br><br>
      <% end %>
    </div>
    <div id="register_container">
      <%= image_tag("up_arrow.png", class: "up_arrow", size: "30", alt: "Up Arrow")  %>
      <%= image_tag("down_arrow.png", class: "down_arrow", size: "30", alt: "Down Arrow")  %>
      <%= form_tag register_path, :id => 'new_user' do %>
        <p><span class="required">*</span> Required Field</p>
        <span class="form">Username<span class="required">*</span></span><br>
        <%= text_field_tag :user_name, nil, class: "form" %><br><br>
        <span class="form">Password<span class="required">*</span></span><br>
        <%= password_field_tag :password, nil, class: "form" %><br><br>
        <span class="form">Confirm Password<span class="required">*</span></span><br>
        <%= password_field_tag :password_confirmation, nil, class: "form" %><br><br>
        <span class="form">First Name<span class="required">*</span></span><br>
        <%= text_field_tag :first_name, nil, class: "form" %><br><br>
        <span class="form">Last Name<span class="required">*</span></span><br>
        <%= text_field_tag :last_name, nil, class: "form" %><br><br>
        <span class="form">Email<span class="required">*</span></span><br>
        <%= email_field_tag :email, nil, class: "form" %><br><br>
        <span class="form">Confirm Email<span class="required">*</span></span><br>
        <%= email_field_tag :email_confirmation, nil, class: "form" %><br><br>
        <%= submit_tag "Register", class: "submit_button" %>
        <%= button_tag(type: 'button', class: 'cancel_button') do content_tag(:strong, 'Cancel') end %><br><br>
      <% end %>
    </div>
    <div id="map_container">
      <iframe width="90%" height="90%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?ie=UTF8&amp;t=m&amp;oe=UTF8&amp;msa=0&amp;msid=211066975015897757609.0004b38aa8e7bdf7d9baf&amp;ll=39.195188,-96.589694&amp;spn=0.013185,0.018282&amp;output=embed"></iframe><br /><small>View <a href="https://maps.google.com/maps/ms?ie=UTF8&amp;t=m&amp;oe=UTF8&amp;msa=0&amp;msid=211066975015897757609.0004b38aa8e7bdf7d9baf&amp;ll=39.195188,-96.589694&amp;spn=0.013185,0.018282&amp;source=embed" style="color:#0000FF;text-align:left">Kansas State University</a> in a larger map</small>
    </div>
  </div>
  <div id="footer">
    <div id ="sticky_footer">
      <%= image_tag("user_icon.png", class: "user_icon", size: "60", alt: "User Login")  %>
      <%= image_tag("map_icon.png", class: "map_icon", size: "60", alt: "Campus Map")  %>
      <%= image_tag("add_user_icon.png", class: "add_user_icon", size: "60", alt: "Register New User")  %>
    </div>
  </div>
</body>
</html>