StudentHomepage/config/routes.rb
StudentHomepage::Application.routes.draw do
  resources :clubs
  resources :students
  resources :instructors

  get 'session' => "home#index"
  get 'login' => "login#new"
  post 'login' => "login#create"
  get 'logout' => "login#destroy"
  get 'register' => "users#new"
  post 'register' => "users#create"
  get 'contact' => "contact#new"
  post 'contact' => "contact#create"

  

  root 'login#new'

end

StudentHomepage/app/models/club.rb
class Club < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, :through => :subscriptions
end

StudentHomepage/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name)
    end
end

StudentHomepage/app/helpers/clubs_helper.rb
module ClubsHelper
end

StudentHomepage/app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StudentHomepage/app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

StudentHomepage/app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

StudentHomepage/app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

StudentHomepage/app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>